# Generated by Django 2.1.10 on 2019-07-17 17:09

import apply.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('apply', '0001_initial'), ('apply', '0002_auto_20190714_1527'), ('apply', '0003_auto_20190714_1537'), ('apply', '0004_auto_20190714_1613'), ('apply', '0005_auto_20190717_1708')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('preferred_name', models.CharField(blank=True, max_length=30, verbose_name='Preferred name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('is_past_applicant', models.BooleanField(verbose_name='Past applicant')),
                ('date_applied', models.DateTimeField(auto_now=True, verbose_name='Date applied')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=5000)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('question_text', models.CharField(max_length=300, verbose_name='Question text')),
                ('question_type', models.CharField(choices=[(apply.models.QuestionType('Long Text'), 'Long Text'), (apply.models.QuestionType('One Line Text'), 'One Line Text'), (apply.models.QuestionType('Single Choice'), 'Single Choice'), (apply.models.QuestionType('Multiple Choice'), 'Multiple Choice')], default=apply.models.QuestionType('Long Text'), max_length=20, verbose_name='Type')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField(verbose_name='Move-in date')),
                ('open_time', models.DateTimeField(verbose_name='Applications form opening time')),
                ('close_time', models.DateTimeField(verbose_name='Applications form closing time')),
                ('voting_close_time', models.DateTimeField(verbose_name='Members voting closing time')),
                ('special_title', models.CharField(blank=True, max_length=30, verbose_name='Special name, e.g. Summerletter')),
                ('voting_open_time', models.DateTimeField(verbose_name='Members voting opening time')),
            ],
            options={
                'ordering': ('-move_in_date',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.Applicant')),
                ('voting_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.ApplicationSession'),
        ),
        migrations.AddField(
            model_name='applicationanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.ApplicationQuestion'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='answers',
            field=models.ManyToManyField(through='apply.ApplicationAnswer', to='apply.ApplicationQuestion'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.ApplicationSession'),
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('session__move_in_date', 'last_name', 'first_name')},
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='question_options',
            field=models.TextField(blank=True, max_length=300, verbose_name='Question options (optional)'),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='question_type',
            field=models.CharField(choices=[('LongText', 'Long Text'), ('ShortText', 'One Line Text'), ('SingleChoice', 'Single Choice'), ('MultipleChoice', 'Multiple Choice')], default=apply.models.QuestionType('Long Text'), max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='verified_past_applicant',
            field=models.BooleanField(default=False, verbose_name='Verified past applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='is_past_applicant',
            field=models.BooleanField(default=False, verbose_name='Past applicant'),
        ),
    ]
