# Generated by Django 2.1.10 on 2019-07-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='applicationsession',
            options={'ordering': ('-move_in_date',)},
        ),
        migrations.AddField(
            model_name='applicationsession',
            name='special_title',
            field=models.CharField(blank=True, max_length=30, verbose_name='Special name, e.g. Summerletter'),
        ),
    ]
