# Generated by Django 2.1.10 on 2019-07-14 15:37

import apply.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20190714_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='question_options',
            field=models.TextField(blank=True, max_length=300, verbose_name='Question options (optional)'),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='question_type',
            field=models.CharField(choices=[('LongText', 'Long Text'), ('ShortText', 'One Line Text'), ('SingleChoice', 'Single Choice'), ('MultipleChoice', 'Multiple Choice')], default=apply.models.QuestionType('Long Text'), max_length=20, verbose_name='Type'),
        ),
    ]
