# Generated by Django 2.1.10 on 2019-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20190720_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='app_team_note',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Applications team notes (invisible to applicant)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='confidential_note',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Confidential information'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Votes received'),
        ),
    ]
