# Generated by Django 2.1.10 on 2019-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20190714_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('session__move_in_date', 'last_name', 'first_name')},
        ),
        migrations.AddField(
            model_name='applicant',
            name='verified_past_applicant',
            field=models.BooleanField(default=False, verbose_name='Verified past applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='is_past_applicant',
            field=models.BooleanField(default=False, verbose_name='Past applicant'),
        ),
    ]
