# Generated by Django 2.1.10 on 2020-02-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20190902_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='visible_in_voting',
            field=models.BooleanField(default=True, verbose_name='Visible for voters'),
        ),
    ]
