# Generated by Django 3.2.21 on 2023-09-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_keep_original_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationquestion',
            name='question_text',
            field=models.CharField(max_length=500, verbose_name='Question text'),
        ),
    ]
