# Generated by Django 5.2.10 on 2026-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0009_alter_applicationquestion_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationvote",
            name="vote",
            field=models.IntegerField(
                choices=[
                    (2, "Exceptional"),
                    (1, "Suitable"),
                    (0, "Abstain"),
                    (-1, "Not suitable"),
                    (-2, "Extremely not suitable"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
    ]
