# Generated by Django 5.2.10 on 2026-04-22 13:59

from django.db import migrations, models


def forwards(apps, schema_editor):
    # Previously:
    # if vote_str == "NOTSUITABLE":
    #     vote = -2
    # elif vote_str == "SUITABLE":
    #     vote = 1
    # elif vote_str == "EXCEPTIONAL":
    #     vote = 2
    # elif vote_str == "ABSTAIN":
    #     vote = 0
    #
    # So only change is to map -2 to -1.
    ApplicationVote = apps.get_model("apply", "ApplicationVote")
    db = schema_editor.connection.alias

    ApplicationVote.objects.using(db).filter(points=-2).update(vote=-1)
    ApplicationVote.objects.using(db).exclude(
        vote=-2).update(vote=models.F("points"))


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0010_remove_applicationvote_points_applicationvote_vote"),
    ]

    operations = [migrations.RunPython(forwards)]
