# Generated by Django 5.2.10 on 2026-04-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0011_renumber_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationvote",
            name="points",
        ),
    ]
