# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='perm_address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
