# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170524_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_number',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
