# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170524_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_number',
            field=models.CharField(blank=True, max_length=8, verbose_name='Bank Reference Number'),
        ),
    ]
