# Generated by Django 1.11.1 on 2017-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20170525_0059"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="share_received",
            field=models.BooleanField(default=False),
        ),
    ]
