# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-02 10:34
from __future__ import unicode_literals

from django.db import migrations, models


def set_default_preferred_name(apps, schema_editor):
    profiles = apps.get_model('users', 'profile')
    for profile in profiles.objects.all().iterator():
        if not profile.preferred_name:
            profile.preferred_name = profile.user.first_name
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_share_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(set_default_preferred_name),
    ]
