# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_extra_ldap_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_member',
            field=models.BooleanField(default=False),
        )
    ]
