# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 11:56
from __future__ import unicode_literals

from django.db import migrations, models


def activate_members(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.all().update(current_member=models.F('share_received'))
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_current_member'),
    ]

    operations = [
        migrations.RunPython(activate_members)
    ]
