# Generated by Django 3.1.14 on 2022-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ldap_groups_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_member',
        ),
        migrations.AddField(
            model_name='profile',
            name='member_status',
            field=models.CharField(choices=[('URG', 'Unregistered'), ('CRT', 'Current'), ('ALM', 'Alumni')], default='URG', max_length=3),
        ),
    ]
