# Generated by Django 3.1.14 on 2022-09-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ldap_groups_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='deposit_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sds_ref_number',
            field=models.CharField(blank=True, max_length=8, verbose_name='SDS Reference Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
        ),
    ]
