# Generated by Django 5.2.10 on 2026-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_profile_sds_ref_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="oidc_sub",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
