# Generated by Django 2.1.10 on 2019-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qboRealmId', models.BigIntegerField(blank=True, verbose_name='(API) QBO Realm ID')),
                ('qboAccessToken', models.CharField(blank=True, max_length=256, verbose_name='(API) QBO Access Toekn')),
                ('qboAccessTimeout', models.DateTimeField(blank=True, verbose_name='(API) QBO Access Expiry')),
                ('qboRefreshToken', models.CharField(blank=True, max_length=256, verbose_name='(API) QBO Refresh Token')),
                ('qboRefreshTimeout', models.DateTimeField(blank=True, verbose_name='(API) QBO Refresh Expiry')),
            ],
        ),
    ]
