# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waliki', '0006_auto_20170326_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='markup',
            field=models.CharField(choices=[('Markdown', 'Markdown')], default='Markdown', max_length=20, verbose_name='Markup'),
        ),
    ]
