# Generated by Django 3.2.25 on 2024-12-15 12:09

import census.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('visible_in_voting', models.BooleanField(default=True, verbose_name='Visible for voters')),
                ('question_text', models.TextField(max_length=5000, verbose_name='Question text')),
                ('question_type', models.CharField(choices=[('LongText', 'Long Text'), ('ShortText', 'Short Text'), ('SingleChoice', 'Single Choice'), ('MultipleChoice', 'Multiple Choice')], default=census.models.QuestionType['LongText'], max_length=20, verbose_name='Type')),
                ('question_options', models.TextField(blank=True, max_length=300, verbose_name='Question options (optional)')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CensusSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_name', models.TextField(verbose_name='Census name (e.g. 2024 Semester 1)')),
                ('open_time', models.DateTimeField(verbose_name='Census form opening time')),
                ('close_time', models.DateTimeField(verbose_name='Census form closing time')),
                ('response_count', models.IntegerField(default=0, verbose_name='Number of responses')),
            ],
            options={
                'ordering': ('-census_name',),
            },
        ),
        migrations.CreateModel(
            name='CensusResponse',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer_text', models.TextField(blank=True, max_length=500000, null=True)),
                ('answer_choice', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.censusquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.censussession', verbose_name='Census session')),
            ],
            options={
                'ordering': ('session',),
            },
        ),
        migrations.AddField(
            model_name='censusquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.censussession'),
        ),
    ]
