# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_vote_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
