# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='point',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='GM',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
