# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='minutes_file',
            field=models.FileField(null=True, upload_to='minutes/'),
        ),
    ]
