# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('home', '0003_gm_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='WgUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.GM')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
        ),
    ]
