# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_wgupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GM'),
        ),
        migrations.AlterField(
            model_name='point',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wgupdate',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GM'),
        ),
        migrations.AlterField(
            model_name='wgupdate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
