# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170725_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='gm',
            name='minutes',
            field=models.FileField(default=None, upload_to='minutes/'),
        ),
    ]
