# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gm_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gm',
            name='minutes',
            field=models.FileField(default=None, null=True, upload_to='minutes/'),
        ),
    ]
