# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170730_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_file', models.FileField(upload_to='minutes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='gm',
            name='minutes',
        ),
        migrations.AddField(
            model_name='minutes',
            name='gm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GM'),
        ),
    ]
