# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170730_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='gm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.GM'),
        ),
    ]
