# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

def migrate_roles(apps, schema_editor):
    Role = apps.get_model('home', 'Role')
    to_remove = []
    main_roles = {}
    for r in Role.objects.all():
        if r.role_name in main_roles:
            to_remove.append(r)
            mr = main_roles[r.role_name]
            if r.assigned_to:
                mr.assigned_to_many.add(r.assigned_to)
            mr.save()
        else:
            main_roles[r.role_name] = r
            if r.assigned_to:
                r.assigned_to_many.add(r.assigned_to)
            r.save()
    for r in to_remove:
        r.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_add_manytomany_role_assign'),
    ]

    operations = [
        migrations.RunPython(migrate_roles),
    ]
