# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_move_role_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='assigned_to',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='assigned_to_many',
            new_name='assigned_to'
        )
    ]
