# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
