# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_auto_20170525_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='building',
            field=models.PositiveIntegerField(verbose_name='building number'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='flat',
            field=models.PositiveIntegerField(verbose_name='flat number'),
        ),
    ]
