# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_auto_20170527_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='date_signed',
            field=models.DateField(default=datetime.date(2017, 5, 27), verbose_name='date signed'),
            preserve_default=False,
        ),
    ]
