# Generated by Django 2.1.10 on 2019-09-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='emergency_contact_address',
            field=models.TextField(default='', max_length=256, verbose_name='emergency contact phone'),
        ),
        migrations.AddField(
            model_name='lease',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='emergency contact name'),
        ),
        migrations.AddField(
            model_name='lease',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=32, verbose_name='emergency contact phone'),
        ),
    ]
