# Generated by Django 3.1.14 on 2022-07-04 21:18

from django.db import migrations, models
import django.db.models.deletion
from datetime import date

def add_rooms_to_leases(apps,schema_editor):
    Lease = apps.get_model('leases','Lease')
    leases = Lease.objects.all()
    Room = apps.get_model('home','Room')
    Flat = apps.get_model('home','Flat')

    for l in leases:
        roomid = ord(l.room_old.upper())-64  # converts room string to int number (A to 1, B to 2 etc)
        f = Flat.objects.get(flatno=l.flat,building=l.building)
        l.room = Room.objects.get(flat=f,roomno=roomid)
        l.save()
        if l.end_date > date.today():
            r = Room.objects.get(id=l.room.id)
            if not r.current_occupant:
                r.current_occupant = l.user
                r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_populate_flatmap'),
        ('leases', '0009_auto_20190910_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='room',
            new_name='room_old'
        ),
        migrations.AddField(
            model_name='lease',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room',null=True),
            preserve_default=False
        ),
        migrations.RunPython(add_rooms_to_leases),
        migrations.RemoveField(model_name='lease',name='building'),
        migrations.RemoveField(model_name='lease',name='flat'),
        migrations.RemoveField(model_name='lease',name='room_old')
        # migrations.AlterField(
        #     model_name='lease',
        #     name='room',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room'),
        # ),
    ]
