# Generated by Django 3.1.14 on 2022-07-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220704_2218'),
        ('leases', '0009_auto_20190910_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='building',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='flat',
        ),
        migrations.AlterField(
            model_name='lease',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room'),
        ),
    ]
