# Generated by Django 3.1.6 on 2022-02-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_auto_20190910_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='covidPos',
            field=models.DateField(null=True, verbose_name='date signed'),
        ),
    ]
