# Generated by Django 3.1.6 on 2022-02-07 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0010_lease_covidpos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='covidPos',
        ),
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.PositiveIntegerField(verbose_name='building number')),
                ('flat', models.PositiveIntegerField(verbose_name='flat number')),
                ('room', models.CharField(max_length=1)),
                ('covid_pos_date', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
