# Generated by Django 3.1.14 on 2022-09-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0010_switch_rooms_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='expected_graduation',
            field=models.DateField(blank=True, null=True, verbose_name='expected graduation date'),
        ),
    ]
