# Generated by Django 3.1.14 on 2022-08-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0010_switch_rooms_to_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='building',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='room_old',
        ),
    ]
