# Generated by Django 3.1.6 on 2022-02-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0011_auto_20220207_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='covid_pos_date',
            field=models.DateField(verbose_name='Positive COVID-19 Test Date'),
        ),
    ]
